### PR TITLE
Hello world!

### PR DESCRIPTION
**Pull request by phil-harmoniq**
Submitting challenges 0-3. I also found 2 typos in the challenge_0 readme.

### CODE REVIEW

**Comment by jarydremillard** [comment]
- [ ] Code review
- [ ] Correct path
- [ ] Check for conflicts
- [ ] **Merge PR**

**Comment by jarydremillard** [comment]
Waiting for response.

**Comment by phil-harmoniq** [comment]
I'm still a programming noob and I'm not exactly sure what that means/how to do it. :/

**Comment by jarydremillard** [comment]
Understood.

Bypassing

**Comment by phil-harmoniq** [comment]
I've been trying to look into what you meant, and I tried to right it a little more efficiently but I'm not sure if it is any better:

```
from collections import Counter

int_array = [2, 2, 3, 7, 5, 7, 7, 7, 4, 7, 2, 7, 4, 5, 6, 7, 7, 8, 6, 7,
             7, 8, 10, 12, 29, 30, 19, 10, 7, 7, 7, 7, 7, 7, 7, 7, 7]

count = Counter(int_array)
answer = count.most_common()

print(answer[0][0])
```

I tried to time the 2 different ways I did it, but both come up as less than 1 ms. Any thoughts?

**Pull request merged**
