### PR TITLE
DakRomo

### PR DESCRIPTION
**Pull request by DakRomo**

### CODE REVIEW

**Comment by jarydremillard** [comment]
- [ ] Code review
- [ ] Correct path
- [ ] Check for conflicts
- [ ] **Merge PR**

**Comment by jarydremillard** [comment]
@DakRomo Please change the path from challenge_1/python/Challenge_1 to the correct format.

challenge_1/python/github_username/main.py

Thank you.

**Comment by DakRomo** [comment]
ok, trying to figure that part out. Changing the path

**Comment by DakRomo** [comment]
@jarydremillard Did I change it to the right path?

**Comment by jarydremillard** [comment]
@DakRomo yup! good job!

**Pull request merged**
