### PR TITLE
Create HelloWorld.R

### PR DESCRIPTION
**Pull request by aev1tas**

### CODE REVIEW

**Comment by jarydremillard** [comment]
- [ ] Code review
- [ ] Correct path
- [ ] Check for conflicts
- [ ] **Merge PR**

**Comment by jarydremillard** [comment]
Code Review:

Do you not have to do
`print ("hello world!", quotes = FALSE)`?

This is on the based that we are executing the code, not simply entering it into a IDE.

**Comment by aev1tas** [comment]
Either/or is fine. https://i.gyazo.com/457c484f8135d006d2f453557e17f01b.png

**Comment by jarydremillard** [comment]
Very well, good enough for me!

**Pull request merged**
