### PR TITLE
[Python] Challenge 2 (Unreviewed)

### PR DESCRIPTION
**Pull request by sarcodian**

### CODE REVIEW

**Comment by whiterd** [comment]
@slandau3 Could you elaborate on what you mean by "Make it so the main function in the script can be activated straight away. Without us having to call it."?  I'm really new to a lot of terminology.

**Comment by whiterd** [comment]
@slandau3 Thank you. That makes perfect sense now. I have a greater appreciation for docstrings after bouncing around different scripts.

**Comment by sarcodian** [comment]
Hello, added the documentation and made it autorun.

**Comment by jarydremillard** [comment]
Bypass

**Pull request merged**
