### PR TITLE
Master

### PR DESCRIPTION
**Pull request by Sphinx111**
Solved in Java :)

### CODE REVIEW

**Comment by Sphinx111** [comment]
Failed to name pull request appropriately, Still learning Sorry! :)

**Comment by jarydremillard** [comment]
Hi Sphinx111,

Could you rename the Java/ directory to java/?

This is to keep a consistent format.

After that, I will review and check for conflicts. If it passes, I will merge the PR.

Thank you.

**Comment by myrrlyn** [comment]
Nicely done. I like the comments and the rationale of your choices.

On Jan 1, 2017 20:07, Sphinx111 <notifications@github.com> wrote:

Solved in Java :)

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/YearOfProgramming/2017Challenges/pull/35

Commit Summary

  *   Create stringReverse.java
  *   Created Java Solution

File Changes

  *   A challenge_1/Java/eddy_north/ReverseString.java<https://github.com/YearOfProgramming/2017Challenges/pull/35/files#diff-0> (26)

Patch Links:

  *   https://github.com/YearOfProgramming/2017Challenges/pull/35.patch
  *   https://github.com/YearOfProgramming/2017Challenges/pull/35.diff

**Comment by jarydremillard** [comment]
You can close the user input way before that. if anything, itd be good to close it right after you get the information you need to prohibit users from inputting information later. its just good safe practice.

reviewed. no conflicts. merging PR.

**Comment by Sphinx111** [comment]
Thanks for the feedback jarydremillard 👍

**Pull request merged**
