### PR TITLE
[python] challenge_0 to _8 Minus 4

### PR DESCRIPTION
**Pull request by sarcodian**

### CODE REVIEW

**Comment by sarcodian** [comment]
Ok, on 3 changed it to // division.
And on 4 added the sample example as a test.

**Comment by ManuelMeraz** [comment]
- [ ] **Code Correctness**
- [ ] **Code Style**
- [ ] **Code Documentation**
- [ ] **Path Structure**
- [ ] **Merge Pull Request**

**Comment by sarcodian** [comment]
Hello Manuel, 

Deleted the folder for solution 4 completely and recommitted so these can pass. But still want to discuss with you on slack regarding 4.

**Comment by sarcodian** [comment]
Any updates to whats pending?

**Pull request closed without merging**
