### PR TITLE
Created my Hello World program

### PR DESCRIPTION
**Pull request by BlakeBarnes00**
Using make to build my programs, I am on Ubuntu so it is best

### CODE REVIEW

**Comment by jarydremillard** [comment]
- [ ] Code review
- [ ] Correct path
- [ ] Code tested
- [ ] Check for conflicts
- [ ] **Merge PR**

**Comment by MJUIUC** [comment]
Good job! I'm not sure if you're aware, but "using namespace std" will get rid of the need for std before you cout. It's not important, but just a tip if you didn't know.

**Comment by jarydremillard** [comment]
bypass

**Comment by BlakeBarnes00** [comment]
@MJUIUC I am aware of that, just it is bad practice in theory. When you have bigger projects you want to be able to identify what you're using where, albeit that this is a simple program using the standard library and all, I would rather keep that in my mind as I learn C++ more.

Thank you for the heads up though!

**Pull request merged**
