### PR TITLE
Python Challenge 1 (Pending)

### PR DESCRIPTION
**Pull request by sonicadept**

### CODE REVIEW

**Comment by jarydremillard** [comment]
- [ ] Code review
- [ ] Correct path
- [ ] Check for conflicts
- [ ] **Merge PR**

**Comment by jarydremillard** [comment]
Code Review:

Straight forward and to the point. Not much to add other than specify what version of python you are using. This could prevent compatibility issues if you ever work as a group.

**Comment by ASethi77** [comment]
- [x] **Code Correctness**
No issues with code correctness. Recommend creating your own test suite in future challenges.
- [x] **Code Style**
No issues with code style.
- [ ] **Code Documentation**
Approach is not documented. Recommend writing a README that discusses how this is a common Python trick and briefly discusses why this works. Writing these kinds of details is ultimately for your own benefit, but will accept a README that links to a discussion of how this works.
- [x] **Other**
Just a side note: I understand that this README request is somewhat silly for this challenge, but we would like people to get used to this habit early, or else we risk documentation falling apart in challenges and projects where this is much more important. We'd like this community to establish good coding practices to make the most out of this project.

**Comment by ManuelMeraz** [comment]
That status of your pull request is pending at the moment. Simple edit out the status when you've implemented the changes we've proposed.

**Comment by jarydremillard** [comment]
@sonicadept

**Pull request closed without merging**
