### PR TITLE
[PostScript] Challenge 3

### PR DESCRIPTION
**Pull request by moonpatroller**

### CODE REVIEW

**Comment by myrrlyn** [comment]
How should we go about checking your work? I've never used PostScript before, and Git is of the opinion that these are binary files so it won't show them on the web. I can pull and check it out locally, but I'd like to know what I'm looking at.

**Comment by MJUIUC** [comment]
I agree with @myrrlyn in that post script may not be the best language to complete challenges with unless you can figure out how to get others to review it.

**Comment by ASethi77** [comment]
I have some concerns that the way we're going is restricting to those who are already experienced and may not want to spend time re-doing best practices stuff or to those who simply don't need the rigor we are requiring but still want to participate in the spirit of YearOfProgramming.

Based on the precedent we've so far, I agree that we should only be merging quality examples to help others learn and understand what a typical coding workflow looks like, and the great thing is that @moonpatroller still has his own fork to show off that he's done this. I'm not sure if this is worth any discussion later...

**Comment by ManuelMeraz** [comment]
Could you leave a README.md documenting your code . This will allow people who may not be familiar with post script to run your code and understand your thought process. Thanks!

**Comment by ManuelMeraz** [comment]
I've added the status pending to the end of your title. Simple edit it out once you've added some documentation for your work. Thanks!

**Comment by jarydremillard** [comment]
@moonpatroller

**Comment by moonpatroller** [comment]
>  myrrlyn commented a day ago
> How should we go about checking your work? I've never used PostScript before, and Git is of the opinion that these are binary files so it won't show them on the web.

Well, you could click the view button that shows you the code...

**Comment by moonpatroller** [comment]
Please review.  Thank You.

**Comment by MJUIUC** [comment]
@moonpatroller No I can't. But even if I could, I don't now post script so I can't give you an honest review. You've decided to do all the challenges in post script, but github won't let us see those files. Even if I were able to DL it, I wouldn't have the first clue how to run it. Hell, repl.it doesn't even support port script. We're sorry for not being blunt earlier, but you cannot use post script to complete the challenges. I'm sorry, but you'll have to find a language we can read if you want us to review it. I'll leave this PR up for another 24 hours, but if nothing comes of it, then I'm closing it. Yes we did say all languages are welcome, but if no one is able to see what you wrote, then it's kind of pointless. Sorry :(

**Comment by moonpatroller** [comment]
I circled the view buttons in red, that will show you the code: http://imgur.com/a/ibaau

> But even if I could, I don't know post script so I can't give you an honest review. 

I didn't ask *you* for a review, but you certainly could read the comments.  I'd at least expect you to look for the View buttons.

> You've decided to do all the challenges in post script, but github won't let us see those files.

It lets me see them when I click on the View buttons, which appear both when I'm logged in and when I'm not.

> Even if I were able to DL it, I wouldn't have the first clue how to run it.

I show the exact command at the top of each file, which is why you should click the view buttons.  And I'm sure you wouldn't immediately know how to run other programs in all other languages...

> Hell, repl.it doesn't even support port script.

What does that have to do with anything?  This is a project where people write and push code from their desktops.

> I'm sorry, but you'll have to find a language we can read if you want us to review it.

You can if you click the View button, but I fear that at this point you'd never admit to being able to see it.

> Yes we did say all languages are welcome, but if no one is able to see what you wrote, then it's kind of pointless.

So if you can read it, it will be accepted, and if I'm not lying about the View button, this will be accepted?  Or will you continue to find other things to complain about?

If that's right and there's really no way you'll accept PostScript even if you can view the source, then can you at least provide a complete list of which languages *are* acceptable before I start using them?

It seems like I'm following all the instructions in the README, and you're still arbitrarily dismissing my efforts.  This is maybe the worst way a public, open source thing like this could be run.

**Comment by moonpatroller** [comment]
@jarydremillard @ManuelMeraz I've done what's requested and even included an image with the view buttons circled so you can all see the source code.  Please help me out here.

**Comment by MJUIUC** [comment]
@moonpatroller I didn't mean to insult you if I did. I tried clicking on the view button when I saw your first PR. We didn't know before hand that Post Script would be an issue. This whole project is literally 4 days old and we thought of it on a whim so of course most things will be rough to start with. Anyway, this is what I see when I hit the view button:

screen shot 2017-01-05 at 3 25 46 pm

As you can see, It's pretty difficult to make something of this no? The average person reviewing this would have no idea what they were looking at. I know you didn't spend all that time writing nothing, so I copied this entire file into an index.html since that's what it looked like, and then I got this:

screen shot 2017-01-05 at 3 30 54 pm

Hey look it's Post Script! Now all we have to do is find a way to test it for you. If you intend on continuing to use Post Script, I recommend just changing the extension to .txt and then in your readme file have a section saying to change the extension back to .ps since I think that's what the issue was.

**Comment by moonpatroller** [comment]
@MJUIUC 
> As you can see, It's pretty difficult to make something of this no?

Yes, but clearly that's not how it functions for me or everyone else, so maybe your browser has an issue?  It's not like github is all buggy in other ways, as far as I see.

> Now all we have to do is find a way to test it for you.

Not really, nothing says you have to do that.

> I recommend just changing the extension to .txt and then in your readme file have a section saying to change the extension back to .ps since I think that's what the issue was.

Ok, I'll do that.

**Comment by moonpatroller** [comment]
Please review.

**Comment by moonpatroller** [comment]
Please review.

**Comment by moonpatroller** [comment]
@MJUIUC I made the requested changes, please review.  "Something has come of it" as you said.

**Comment by moonpatroller** [comment]
@jarydremillard What's going on here?

**Comment by moonpatroller** [comment]
@myrrlyn Are you around anymore?  You seemed willing to look at the files before, and I've renamed them so it should be easy for you to see them on the website...

**Comment by ASethi77** [comment]
I'm going to go ahead and merge this. While we don't know PostScript well enough to really meet the original 3-person review requirement the logic is simple enough that your code definitely looks reasonable, and you're following the README + our requests otherwise.

Nice work! Sorry that this has happened.

**Comment by moonpatroller** [comment]
Wow, thanks a lot.

**Pull request merged**
