### PR TITLE
Create challenge_0

### PR DESCRIPTION
**Pull request by Jzanet**
A simple "hello world" code with print function

### CODE REVIEW

**Comment by ManuelMeraz** [comment]
- [ ] Code review
- [ ] Correct path
- [ ] Check for conflicts
- [ ] **Merge PR**

**Comment by ManuelMeraz** [comment]
Hey there, simply update your directory path for your username from Zanetti to zanetti :) and we can merge your code.

**Comment by myrrlyn** [comment]
Do we want to enforce lowercase on usernames? Enforced language case makes sense, but I don't think we need to worry about it too much for usernames.

As long as we don't have "User" and "user" folders as siblings to break Windows and OSX filesystems, I don't think it'll matter?

On Jan 2, 2017 08:59, Manuel Meraz <notifications@github.com> wrote:

Hey there, simply update your directory path for your username from Zanetti to zanetti :) and we can merge your code.

**Comment by ManuelMeraz** [comment]
@myrrlyn Makes perfect sense!

**Comment by Jzanet** [comment]
Sorry about that. I'll correct that as soon as possible =)

**Pull request merged**
