### PR TITLE
[C++] Challenge 7 (Unreviewed)

### PR DESCRIPTION
**Pull request by ManuelMeraz**

### CODE REVIEW

**Comment by karanchawla** [comment]
- [x] **Code Correctness**
- [x] **Code Style**
- [ ] **Code Documentation**
- [x] **Path Structure**
- [ ] **Merge Pull Request**

**Comment by ManuelMeraz** [comment]
@karanchawla There is a README documenting the process if you scroll down. Here's a link to the file https://github.com/ManuelMeraz/2017Challenges/blob/e5de15d0bb42663415e55e18684717e0ba30d997/challenge_7/cpp/manuel/README.md

**Comment by karanchawla** [comment]
@ManuelMeraz That's alright. You should have comments in the function definition and your main file too IMO

**Comment by ManuelMeraz** [comment]
@karanchawla I guess you're right! I didn't comment them because I thought the function names were self explanatory. I'll add in some comments.

**Pull request merged**
