### PR TITLE
Create challenge_1

### PR DESCRIPTION
**Pull request by Jzanet**
SImple code to invert a given list using the list(), input() and .reverse() functions

### CODE REVIEW

**Comment by ManuelMeraz** [comment]
- [ ] Code review
- [ ] Correct path
- [ ] Check for conflicts
- [ ] **Merge PR**

**Comment by ManuelMeraz** [comment]
It looks like your code does not work correctly. You're almost there though! Just convert the list back to a string.

Here's the output I get with the input 'test'
```
Insert the  you want to invert :test
the choosen world:  ['t', 'e', 's', 't']
reversed:  ['t', 's', 'e', 't']
```

**Comment by jarydremillard** [comment]
Code Review:

Technically, this works. But using user input for this case is iffy, especially since there was no check for integrity. Besides, not only are you limiting yourself to just a string, but if you actually set it to a variable, you could reverse strings and lists. Other than that, way to keep it minimal! I like concise code!

**Comment by Jzanet** [comment]
Ok, Thanks, I'll correct them as soon as possible.

**Pull request merged**
