### PR TITLE
String reverse for ruby

### PR DESCRIPTION
**Pull request by ConorWright**

### CODE REVIEW

**Comment by jarydremillard** [comment]
Hi Conor,

Please change the path of Challenge_1/ to challenge_1

From there I can merge your PR.

Thank you.

**Comment by jarydremillard** [comment]
@myrrlyn having issues with local repo still as Challenge_1

figured you might be able to help

**Comment by ConorWright** [comment]
Fixed it the good old xkcd way. Should be good to go.

**Comment by jarydremillard** [comment]
- [ ] Code review
- [ ] Correct path
- [ ] Check for conflicts
- [ ] **Merge PR**

**Comment by jarydremillard** [comment]
Code Review:

Good use of bang!
Straightforward and to the point. Nothing really to comment about!

**Pull request merged**
